apiVersion: v1  #k8 version
kind: Service    # k8s resource we are creating
metadata:
  name: springboot-k8s-service
spec:
  selector:
    app: springboot-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # port the service is running on the cluster
      targetPort: 8080 #port exposed by serive
  type: NodePort